### ISSUE TITLE
Missing Subscribe button in newsletter form (Magento 2.3.2)

### ISSUE THREAD

**Issue by tangar76** [swissup/module-font-awesome#4]
When module enabled then "Subscribe" button is hidden in newsletters subscription form.
It is because of CSS class "sr-only".

https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Newsletter/view/frontend/templates/subscribe.phtml#L36

**Comment by SimpleCode11** [comment]
Hello,
on my page the subscription button has disappeared after upgrading to Magento 2.3.2

Do you know the solution to the problem?

**Comment by vovayatsyuk** [comment]
Hi,
this issue (https://github.com/magento/magento2/issues/24027) is already fixed in [2.3-develop branch](https://github.com/magento/magento2/commit/9279b695156d1c92149459115db10b4ebf832881#diff-21354d32dbb20e4e118290198fbd4fbf). 

You can apply this patch manually for now or remove the `sr-class` with [custom javascript](https://github.com/magento/magento2/issues/24027#issuecomment-524003871).

**Comment by SimpleCode11** [comment]
Thank you :)

**Comment by roma84** [comment]
The fix was included in Magento 2.3.4.
